version: "3"

networks:
  cv:
    external: false

services:
  node:
    networks:
      - cv
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./src:/home/node/app
